#cloud-config
datasource:
  Ec2:
    strict_id: false
ssh_pwauth: no
users:
- name: ubuntu
  sudo: 'ALL=(ALL) NOPASSWD:ALL'
  shell: /bin/bash
  ssh_authorized_keys:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAI/EG5UfNnSxWsNBP0qo3Jrv2FkQlHbOypXXFxLpIM6
packages:
  - unzip
  - python3-pip
  - git
  - jq
write_files:
  - path: "/usr/local/etc/startup.sh"
    content: |
      #!/bin/bash

      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      chmod +x kubectl && sudo mv kubectl /usr/local/bin
      curl -LO "https://hashicorp-releases.yandexcloud.net/terraform/1.8.5/terraform_1.8.5_linux_amd64.zip"
      sudo unzip -u terraform_1.8.5_linux_amd64.zip -d /usr/local/bin && rm terraform_1.8.5_linux_amd64.zip
      curl -LO https://get.helm.sh/helm-v3.17.1-linux-amd64.tar.gz
      tar xvf helm-v3.17.1-linux-amd64.tar.gz && sudo mv linux-amd64/helm /usr/local/bin
      rm helm-v3.17.1-linux-amd64.tar.gz && rm -rf linux-amd64
      export HOME=/home/ubuntu; curl -L https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
      mkdir -p /home/ubuntu/keys
      git clone https://github.com/borbul2007/diplom.git /home/ubuntu/diplom && chown -R ubuntu:ubuntu /home/ubuntu/diplom
      git clone https://github.com/kubernetes-sigs/kubespray.git /home/ubuntu/kubespray && chown -R ubuntu:ubuntu /home/ubuntu/kubespray
    permissions: '0755'
    defer: true
runcmd:
  - ["/usr/local/etc/startup.sh"]